/*
Update date: 2018-08-24
Updated by: Yuhui Xu
Reason: Added =iable labels for snap pea, snow pea, other pea, and loose leaf

2020-02-04 Anna Manore
Added =iables fbeefpatties, sausage_beef, sausage_pork, sausage_chick, sausage_turk, 
sausage_o, frozendairy, cheesenond, kale, saladkit, vegferm, osaladstore, prefruitsm,
salsa_f, salsa_jar, dough, pettingzoo to this and the french version 

2024-02-01 Megan Tooby
Updated for Foodbook 2.0
*/


*Vegetables and herbs in FB 2 
gen label = "Any tomato" if exposure == "anytom"
replace label = "Cherry or grape tomatoes" if exposure == "tomcherry"
replace label = "Any lettuce or leafy greens" if exposure == "anylettuce"
replace label = "Iceberg lettuce" if exposure == "iceberg"
replace label = "Romaine lettuce" if exposure == "romaine"
replace label = "Spinach" if exposure == "spinach"
replace label = "Mesclun greens"  if exposure == "mesclun"
replace label = "Kale" if exposure == "kale"
replace label = "Arugula" if exposure == "arugula"
replace label = "Other leafy greens" if exposure == "olettuce"
replace label = "Any pre-packaged leafy greens, whole or chopped" if exposure == "prepacklg"
replace label = "Any commercially pre-packaged salad kits" if exposure == "saladkit"
replace label = "Cabbage" if exposure == "cabbage"
replace label = "Any coleslaw" if exposure == "coleslaw"
replace label = "Any store-bought prepared or ready to eat green salads" if exposure == "greensal"
replace label = "Mini carrots" if exposure == "minicar"
replace label = "Sprouts or microgreens" if exposure == "sprouts"
replace label = "Alfalfa sprouts" if exposure == "alfalfa"
replace label = "Bean sprouts" if exposure == "beansprouts"
replace label = "Any microgreens" if exposure == "microgreens"
replace label = "Other sprouts or microgreens" if exposure == "osprout"
replace label = "Cucumbers" if exposure == "cucumbers"
replace label = "Bell peppers" if exposure == "bpeppers"
replace label = "Hot peppers" if exposure == "hotpeppers"
replace label = "Sugar snap peas" if exposure == "snappea"
replace label = "Mushrooms" if exposure == "mushroom"
replace label = "Any onions" if exposure == "onions"
replace label = "Red onions" if exposure == "redonion"
replace label = "Green onions" if exposure == "grnonion"
replace label = "Other onion" if exposure == "oonion"
replace label = "Basil" if exposure == "anybasil"
replace label = "Fresh cilantro/coriander" if exposure == "cilantro"
replace label = "Fresh parsley" if exposure == "parsley"
replace label = "Other fresh herbs" if exposure == "ofherb"

*Vegetables and herbs in FB1 only
replace label = "Celery*" if exposure == "celery"
replace label = "Carrots*" if exposure == "carrot"
replace label = "Peas*" if exposure == "pea"
replace label = "Green or yellow beans*" if exposure == "gybeans"
replace label = "Broccoli*" if exposure == "broccoli"
replace label = "Cauliflower*" if exposure == "cauliflo"
replace label = "Leeks*" if exposure == "leek"
replace label = "Fresh garlic*" if exposure == "garlic"
replace label = "Zucchini*" if exposure == "zucchini"
replace label = "Vegetable juice*" if exposure == "vegjuice"
replace label = "Frozen vegetables*" if exposure == "vegez"

*Fruits in FB 2
replace label = "Mangos" if exposure == "mango"
replace label = "Fresh mangos" if exposure == "mango_f"
replace label = "Frozen mangos" if exposure == "mango_z"
replace label = "Dried mangos" if exposure == "mango_d"
replace label = "Papayas" if exposure == "papaya"
replace label = "Fresh papayas" if exposure == "papaya_f"
replace label = "Frozen papayas" if exposure == "papaya_z"
replace label = "Dried papayas" if exposure == "papaya_d"
replace label = "Pomegranate" if exposure == "pomegra"
replace label = "Fresh pomegranate" if exposure == "pomegra_f"
replace label = "Frozen pomegranate" if exposure == "pomegra_z"
replace label = "Avocado" if exposure == "avocado"
replace label = "Fresh avocado" if exposure == "avocado_f"
replace label = "Frozen avocado" if exposure == "avocado_z" 
replace label = "Any melon" if exposure == "melon"
replace label = "Cantaloupe" if exposure == "cantaloup"
replace label = "Fresh cantaloupe" if exposure == "cantaloup_f"
replace label = "Frozen cantaloupe" if exposure == "cantaloup_z"
replace label = "Honeydew melon" if exposure == "honeydew"
replace label = "Fresh honeydew melon" if exposure == "honeydew_f"
replace label = "Frozen honeydew melon" if exposure == "honeydew_z"
replace label = "Watermelon"  if exposure == "watermel"
replace label = "Fresh watermelon" if exposure == "watermel_f"
replace label = "Frozen watermelon" if exposure == "watermel_z" 

replace label = "Peaches" if exposure == "peach"
replace label = "Fresh peaches" if exposure == "peach_f"
replace label = "Frozen peaches" if exposure == "peach_z"
replace label = "Nectarines" if exposure == "nectarine"
replace label =  "Fresh nectarines" if exposure == "nectarine_f"
replace label =  "Frozen nectarines" if exposure == "nectarine_z"
replace label =  "Strawberries" if exposure == "strawb"
replace label =  "Fresh strawberries" if exposure == "strawb_f"
replace label =  "Frozen strawberries" if exposure == "strawb_z"
replace label =  "Dried strawberries" if exposure == "strawb_d"
replace label =  "Raspberries" if exposure == "raspb"
replace label =  "Fresh raspberries" if exposure == "raspb_f"
replace label =  "Frozen raspberries" if exposure == "raspb_z"
replace label =  "Dried raspberries" if exposure == "raspb_d"
replace label =  "Blueberries" if exposure == "blueb"
replace label =  "Fresh blueberries" if exposure == "blueb_f"
replace label =  "Frozen blueberries" if exposure == "blueb_z"
replace label =  "Dried blueberries" if exposure == "blueb_d" 
replace label =  "Blackberries" if exposure == "blackb"
replace label =  "Fresh blackberries" if exposure == "blackb_f"
replace label =  "Frozen blackberries" if exposure == "blackb_z"
replace label =  "Dried blackberries" if exposure == "blackb_d"
replace label =  "Coconut" if exposure == "coconut"
replace label =  "Fresh coconut" if exposure == "coconut_f"
replace label =  "Frozen coconut" if exposure == "coconut_z"
replace label =  "Dried/shredded coconut" if exposure == "coconut_d"
replace label =  "Bag of mixed frozen fruit or berries" if exposure == "fruitz"
replace label =  "Unpasteurized apple cider or fruit juice" if exposure == "unpjuice"
replace label =  "Fruit smoothies" if exposure == "fruitsm"
replace label = "Any berries" if exposure == "anyberry"
replace label = "Any melon" if exposure == "melon"

*Fruits in FB 1 only
replace label =  "Apples*" if exposure == "apple"
replace label =  "Pears*" if exposure == "pear"
replace label =  "Apricots*" if exposure == "apricot"
replace label =  "Plums*" if exposure == "plum"
replace label =  "Citrus fruit*" if exposure == "citrus"
replace label =  "Cherries*" if exposure == "cherry"
replace label =  "Grapes*" if exposure == "grape"
replace label =  "Bananas*" if exposure == "banana"
replace label =  "Kiwi*" if exposure == "kiwi"
replace label =  "Pineapple*" if exposure == "pineapple"
replace label =  "Olives*" if exposure == "olive"
replace label =  "Red grapes*" if exposure == "redgrape"
replace label =  "Green grapes*" if exposure == "greengr"
replace label =  "Dried fruit*" if exposure == "dryfruit"
replace label =  "Frozen berries*" if exposure == "berriesz"
replace label =  "Frozen fruit*" if exposure == "fruitz"
replace label = "Fruit salad*" if exposure == "fruitsal"

*Nuts and seeds FB 2
replace label =  "Any nuts- on their own, mixed, as a butter/spread or nut milk, in granola bar, as a garnish or as part of a dish" if exposure == "anynuts"
replace label =  "Peanuts" if exposure == "peanut"
replace label =  "Peanut butter" if exposure == "pnbutter"
replace label =  "Almonds" if exposure == "almond"
replace label =  "Almond butter" if exposure == "almondbutter"
replace label =  "Walnuts" if exposure == "walnut"
replace label =  "Hazelnuts" if exposure == "hazelnut"
replace label =  "Hazelnut spread" if exposure == "hazelnutbutter"
replace label =  "Cashews" if exposure == "cashew"
replace label =  "Cashew butter" if exposure == "cbutter"
replace label =  "Pecans" if exposure == "pecan"
replace label =  "Other nut" if exposure == "onut"
replace label =  "Sunflower seeds" if exposure == "sunflwsd"
replace label =  "Sunflower seed butter or paste" if exposure == "sunbutter"
replace label =  "Sesame seeds" if exposure == "sesamesd"
replace label =  "Tahini, incuding in home-made hummus" if exposure == "tahini"
replace label =  "Chia seeds/chia seed powder" if exposure == "chia"
replace label =  "Flax seeds/flax seed powder" if exposure == "flax"
replace label =  "Other seed" if exposure == "oseed"

*Nuts and seeds in FB1 only
replace label =  "Other nut butters/spreads*" if exposure == "nutpaste"

*Beef FB 2
replace label =  "Beef (not including deli-meats)" if exposure == "anybeef"
replace label =  "Any ground beef" if exposure == "anygroundbeef"
replace label =  "Ground beef consumed raw or undercooked (e.g. tartare or kibbeh)" if exposure == "bgroundraw"
replace label =  "Hamburgers (i.e. hamburger patties)" if exposure == "hamb"
replace label =  "Hamburgers store-bought frozen beef patties" /* fbeefpatties was pulling into the analysistemplate excel doc */ if exposure == "zbeefpatties"
replace label =  "Raw beef" if exposure == "rawb"
replace label =  "Steak" if exposure == "steak"
replace label =  "Stewing beef" if exposure == "stewingb"
replace label =  "Veal" if exposure == "veal"
replace label =  "Beef sausage (excluding dried)" if exposure == "sausage_beef"
replace label =  "Other whole-cut beef products (e.g. ribs or roast)" if exposure == "obwhole"
replace label =  "Whole-cut beef products (e.g. steak, stewing beef, ribs or roast)" if exposure == "bwhole"

*Beef in FB1 only
replace label =  "Beef hamburgers from a restaurant or fast food establishment*" if exposure == "hambrest"
replace label =  "Hamburgers home-made from ground beef*" if exposure == "hambhome"
replace label =  "Other ground beef (e.g. meatball, chilli or spaghetti sauce)*" if exposure == "bground"

*Pork FB 2
replace label = "Pork (not including deli-meats)" if exposure == "anypork"
replace label =  "Ground pork" if exposure == "pground"
replace label =  "Pork pieces or parts" if exposure == "porkparts"
replace label =  "Pork sausage (excluding dried)" if exposure == "sausage_pork"
replace label =  "Pork consumed raw or undercooked with pink still showing" if exposure == "rpork"

*Pork in FB 1 only
replace label =  "Ham (not including deli-meats)*" if exposure == "ham"
replace label =  "Bacon*" if exposure == "bacon"

*Poultry FB 2 
replace label =  "Any chicken (not including deli-meats)" if exposure == "anychick"
replace label =  "Store-bought breaded chicken (e.g. chicken nuggets, strips or burgers)" if exposure == "cbreaded"
replace label =  "Store-bought breaded chicken purchased frozen" if exposure == "zcbreaded"
replace label =  "Store-bought stuffed chicken products (for example, chicken Kiev, chicken Cordon Bleu)" if exposure == "cstuffed"
replace label =  "Store-bought stuffed chicken products purchased frozen" if exposure == "zcstuffed"
replace label =  "Ground chicken" if exposure == "cground"
replace label =  "Chicken pieces or parts" if exposure == "chickparts"
replace label =  "Whole chicken purchased raw and cooked at home" if exposure == "wholec"
replace label =  "Roasted whole chicken" if exposure == "rawwholec"
replace label =  "Chicken sausage (excluding dried)" if exposure == "sausage_chick"
replace label =  "Turkey (not including deli-meat)" if exposure == "anyturk"
replace label =  "Ground turkey" if exposure == "tground"
replace label =  "Turkey pieces or parts" if exposure == "turkparts"
replace label =  "Turkey sausage (excluding dried)" if exposure == "sausage_turk"
replace label =  "Whole turkey" if exposure == "wholet"
replace label =  "Other poultry" if exposure == "poultryo"

*Poultry not in FB 2
replace label =  "Turkey bacon*" if exposure == "tbacon"

*Deli meats and other meats
replace label =  "Deli-meat/cold cuts" if exposure == "deliany"
replace label =  "Chicken deli meat" if exposure == "chickdeli"
replace label =  "Turkey deli meat" if exposure == "turkdeli"
replace label =  "Ham deli meat" if exposure == "hamdeli"
replace label =  "Beef deli meat" if exposure == "beefdeli"
replace label =  "Other deli meat" if exposure == "odeli"
replace label =  "Hot dogs" if exposure == "hotdog"
replace label =  "Pâté/meat spread" if exposure == "pate"
replace label =  "Organ meats or offal (e.g. liver, kidney or heart)" if exposure == "organ"
replace label =  "Veal or calf liver" if exposure == "vliver"
replace label =  "Veal or calf liver consumed raw or undercooked" if exposure == "rawliver"
replace label =  "Other organ meat" if exposure == "oorgan"
replace label =  "Goat" if exposure == "goat"
replace label =  "Lamb" if exposure == "lamb"
replace label =  "Horse" if exposure == "horse"
replace label =  "Dried/cured meat products (e.g. beef jerky)" if exposure == "driedmeat"
replace label =  "Hunted or farmed deer" if exposure == "deer"
replace label =  "Other hunted meats (excluding seafood)" if exposure == "huntedmeats"

*Deli-meats and other meats in FB 1 only
replace label =  "Bologna*" if exposure == "bologna"
replace label =  "Salami*" if exposure == "salami"
replace label =  "Pepperoni*" if exposure == "pepperoni"
replace label =  "Sausage*" if exposure == "sausage"

*Seafood in FB 2
replace label =  "Any seafood" if exposure == "seafood"
replace label =  "Any fish" if exposure == "anyfish"
replace label =  "Smoked fish (e.g. smoked salmon)" if exposure == "fishsmoke"
replace label =  "Raw fish (e.g. sushi, tartare, sashimi or ceviche)" if exposure == "fishraw"
replace label =  "Shellfish" if exposure == "shellfish"
replace label =  "Mussels" if exposure == "mussels"
replace label =  "Clams" if exposure == "clams"
replace label =  "Shrimp/ prawns" if exposure == "shrimp"
replace label =  "Oysters" if exposure == "oysters"
replace label =  "Raw oysters" if exposure == "oysters_r"

*Seafood not in FB 2
replace label =  "Scallops*" if exposure == "scallops"
replace label =  "Crab*" if exposure == "crab"
replace label =  "Shrimp/Prawns*" if exposure == "prawns"
replace label =  "Crayfish" if exposure == "crayfish"
replace label =  "Lobster*" if exposure == "lobster"

*Eggs
replace label =  "Eggs" if exposure == "egg"
replace label =  "Raw or undercooked eggs" if exposure == "eggraw"

*Dairy FB 2 
replace label =  "Ice cream" if exposure == "icecream"
replace label =  "Milk-containing Dessert" if exposure == "milkdess"
replace label =  "Yogurt" if exposure == "yogurt"
replace label =  "Unpasteurized (raw) dairy milk, excluding cheese" if exposure == "milkunpas"
replace label =  "Any cheese products" if exposure == "anycheese"
replace label =  "Gouda" if exposure == "gouda"
replace label =  "Feta cheese" if exposure == "feta"
replace label =  "Brie, camembert or other soft cheeses" if exposure == "scheese"
replace label =  "Cheese made from goat milk" if exposure == "gscheese"
replace label =  "Cheese made with unpasteurized (raw) milk" if exposure == "cheeseunpas"
replace label =  "Non-dairy milk" if exposure == "milko"
replace label =  "Other non-dairy products/substitutes" if exposure == "nondairyo"

*Dairy not in FB 2
replace label =  "Pasteurized dairy milk*" if exposure == "milkpas"
replace label =  "Powdered milk product*" if exposure == "pwdmilk"
replace label =  "Whipped/whipping cream*" if exposure == "whipcream"
replace label =  "Sour cream*" if exposure == "sourcream"
replace label =  "Cheddar cheese*" if exposure == "cheddar"
replace label =  "Mozzarella*" if exposure == "mozz"
replace label =  "Parmesan cheese*" if exposure == "parm"
replace label =  "Other cheeses sold as blocks or cut from solid blocks or wheels*" if exposure == "hrdcheese"
replace label =  "Blue-veined cheese such as blue cheese or gorgonzola*" if exposure == "bvcheese"
replace label =  "Cottage, ricotta or other fresh cheese*" if exposure == "fcheese"
replace label =  "Processed cheese (e.g. sliced cheese, cheese string/tubes or from a jar)*" if exposure == "procheese"

*Other foods
replace label =  "Plant based meat substitute" if exposure == "pbmeat"
replace label =  "Tofu" if exposure == "tofu"
replace label =  "Other plant based meat substitute" if exposure == "soyprod"
replace label =  "Dietary or nutritional supplement (e.g. meal replacements, protein powder)" if exposure == "supp"
replace label =  "Meal replacement beverage" if exposure == "mealrepbev"
replace label =  "Protein powder" if exposure == "protpowder"
replace label =  "Probiotics" if exposure == "probiotics"
replace label =  "Any food or drink containing cannabis as an ingredient" if exposure == "cannabis"
replace label =  "Hummus" if exposure == "hummus"
replace label =  "Flour" if exposure == "flour"
replace label =  "Raw dough or batter made with flour" if exposure == "dough"
replace label =  "Other flour (e.g., almond)" if exposure == "oflour"

*Other foods only in FB1
replace label =  "Chocolate or chocolate containing candy*" if exposure == "choc"
replace label =  "Cold breakfast cereal*" if exposure == "coldbc"
replace label =  "Hot breakfast cereal*" if exposure == "hotbc"
replace label =  "Frozen pizza*" if exposure == "pizza"
replace label =  "Frozen potpie*" if exposure == "potpie"
replace label =  "Frozen meals*" if exposure == "frozenm"
replace label =  "Frozen snacks*" if exposure == "frozens"
replace label =  "Chicken shawarma/donair*" if exposure == "Q91_1"
replace label =  "Beef shawarma/donair*" if exposure == "Q91_2"
replace label =  "Pork shawarma/donair*" if exposure == "Q91_3"
replace label =  "Lamb shawarma/donair*" if exposure == "Q91_4"
replace label =  "Turkey shawarma/donair*" if exposure == "Q91_5"
replace label =  "Veal shawarma/donair*" if exposure == "Q91_6"
replace label =  "Mixed meats shawarma/donair*" if exposure == "Q91_7"
replace label =  "Other type of shawarma/donair*" if exposure == "Q91_8"
replace label =  "Don't know or not sure type of shawarma/donair*" if exposure == "Q91_97"
replace label =  "Refused to answer the type of shawarma/donair*" if exposure == "Q91_99"
replace label =  "Shawarma/donair in a sit-down restaurant*" if exposure == "Q92_1"
replace label =  "Shawarma/donair in a take-out restaurant*" if exposure == "Q92_2"
replace label =  "Shawarma/donair in a food stand*" if exposure == "Q92_3"
replace label =  "Shawarma/donair in other places*" if exposure == "Q92_4"
replace label =  "Don't know or not sure where the shawarma/donair was purchased*" if exposure == "Q92_97"
replace label =  "Refused to answer where the shawarma/donair was purchased*" if exposure == "Q92_99"
replace label =  "Pepper*" if exposure == "Q34_A"
replace label =  "Curry powder*" if exposure == "Q34_B"
replace label =  "Paprika*" if exposure == "Q34_C"
replace label =  "Turmeric*" if exposure == "Q34_D"
replace label =  "Other spices*" if exposure == "Q34_E"
replace label =  "Chips*" if exposure == "chips"
replace label =  "Baby formula as a liquid*" if exposure == "Q1"
replace label =  "Store-bought prepared salads*" if exposure == "csalad"
replace label =  "Store-bought prepared potato salad*" if exposure == "psaladstor"
replace label =  "Store-bought prepared pasta salad*" if exposure == "pastasal"
replace label =  "Store-bought fruit salad/platter*" if exposure == "fruitsal"
replace label =  "Store-bought salsa*" if exposure == "salsa"
replace label =  "Infant/toddler cereal*" if exposure == "Q4"
replace label =  "Eaten any other foods?*" if exposure == "Q5"
replace label =  "Asian style foods (e.g. Chinese, Vietnamese or Thai)*" if exposure == "Q109_A"
replace label =  "Indian style foods*" if exposure == "Q109_B"
replace label =  "Mexican style foods*" if exposure == "Q109_C"
replace label =  "Meal from a fast food restaurant*" if exposure == "Q110_Q111_dv"
replace label =  "Fast food frequency*" if exposure == "Q111"
replace label =  "Fast food burger*" if exposure == "Q112_A"
replace label =  "Fast food sub/sandwich*" if exposure == "Q112_B"
replace label =  "Fast food fried chicken*" if exposure == "Q112_C"
replace label =  "Mexican fast food*" if exposure == "Q112_D"
replace label =  "Fast food pizza*" if exposure == "Q112_E"
replace label =  "Fast food hot dog*" if exposure == "Q112_F"
replace label =  "Other fast food*" if exposure == "Q112_G"

*Food purchasing 
replace label =  "Meat from a butcher shop" if exposure == "butcher"
replace label =  "Food from farmers market or farm" if exposure == "farmfood"
replace label =  "Produce from farmers market or farm" if exposure == "farmproduce"
replace label =  "Egg from farmers market or farm" if exposure == "farmegg"
replace label =  "Meat from farmers market or farm" if exposure == "farmmeat"
replace label =  "Dairy from farmers market or farm" if exposure == "farmdairy"
replace label =  "Food from a meal kit" if exposure == "mealkit"
replace label =  "Food from Goodfood" if exposure == "goodfood"
replace label =  "Food from Hello Fresh" if exposure == "hellofresh"
replace label =  "Food from Chefs Plate" if exposure == "chefsplate"
replace label =  "Food from other meal kit" if exposure == "omealkit"

*Animal questions FB 2
replace label =  "Contact with a domestic animal" if exposure == "domanim"
replace label =  "Contact with any cat" if exposure == "domanim_cat"
replace label =  "Contact with any dog" if exposure == "domanim_dog"
replace label =  "Contact with any bird" if exposure == "domanim_bird"
replace label =  "Contact with any rabbit" if exposure == "domanim_rabbit"
replace label =  "Contact with any hedgehog" if exposure == "domanim_hedgehog"
replace label =  "Contact with any reptile or amphibian or their enclosure" if exposure == "domanim_reptile"
replace label =  "Contact with any rodent" if exposure == "domanim_rodent"
replace label =  "Handle any raw pet food (store-bought or hand-made)" if exposure == "animfdraw"
replace label =  "Handle any treats derived from animal parts (e.g. pig ears)" if exposure == "animfdparts"
replace label =  "Handle any processed animal treats (e.g. chews or biscuits)" if exposure == "animfdproc"
replace label =  "Handle any rodents for reptiles (e.g. feeder mice)" if exposure == "animfdrodent"
replace label =  "Contact with any pet food or treats" if exposure == "animfd"
replace label =  "Contact with a farm animal" if exposure == "ndomanim"
replace label =  "Handle any dry pet food" if exposure == "animfddry"
replace label =  "Contact with any pig" if exposure == "pig"
replace label =  "Contact with any poultry/ baby poultry (e.g. chicks, goslings or turkeys)" if exposure == "poultry"
replace label =  "Contact with cattle" if exposure == "cattle"
replace label =  "Contact with any goat or sheep" if exposure == "goat_sheep"

*Animal questions not in FB 2
replace label =  "Petting zoo*" if exposure == "pettingzoo"
replace label =  "Contact with any amphibian (e.g. frogs, newts or salamanders)*" if exposure == "amphi"
replace label =  "Contact with any fish or aquarium*" if exposure == "aquari"
replace label =  "Contact with any horse*" if exposure == "horse"
replace label =  "Handle any canned/wet pet food*" if exposure == "animfdwet"
replace label =  "Handle any farm animal/livestock feed*" if exposure == "livestockfd"

*Water questions FB 2
replace label =  "Swim in natural water" if exposure == "swim"
replace label = "Municipal water" if exposure == "water_municipal"
replace label = "Bottled water" if exposure == "water_bottled"
*Water FB 1
replace label =  "Type of private well*" if exposure == "Q114"
replace label =  "Treatment system for drinking water*" if exposure == "Q115"
replace label =  "Reverse osmosis*" if exposure == "Q116_1"
replace label =  "Carbon filter*" if exposure == "Q116_2"
replace label =  "Ultraviolet (UV) light*" if exposure == "Q116_3"
replace label =  "Chlorine*" if exposure == "Q116_4"
replace label =  "Other filter*" if exposure == "Q116_5"
replace label =  "Don't know or not sure what in-home treatment system is being used*" if exposure == "Q116_97"
replace label =  "Refused to answer the type of in-home treatment system being used*" if exposure == "Q116_99"
replace label =  "Primary reason for treating drinking water*" if exposure == "Q117"
replace label =  "Drink any lake, spring or river water excluding your home water supply*" if exposure == "Q118"
replace label =  "Go into an ocean*" if exposure == "Q120_A"
replace label =  "Go into a lake*" if exposure == "Q120_B"
replace label =  "Go into a river*" if exposure == "Q120_C"
replace label =  "Go into a natural hot spring*" if exposure == "Q120_D"

*Labels added for variables only in case data and not in Foodbook
replace label =  "Other animal food" if exposure == "animfdother"
replace label =  "Any animal treats" if exposure == "animtreat"
replace label =  "Other animal treats" if exposure == "animtreatother"

replace label =  "Other ground beef" if exposure == "bgroundo"
replace label =  "Other chicken" if exposure == "chicko"
replace label =  "Other dairy" if exposure == "dairyo"
replace label =  "Attends daycare" if exposure == "daycare"
replace label =  "Deli meat sliced at the deli counter" if exposure == "delicounter"
replace label =  "Pre-packaged deli meat" if exposure == "deliprepk"
replace label =  "Other domestic animal" if exposure == "domanim_other"
replace label =  "Any dried herbs or spices" if exposure == "driedherb"
replace label =  "Work/volunteer as a food handler" if exposure == "fdhand"
replace label =  "Ginger" if exposure == "ginger"
replace label =  "Handled raw chicken" if exposure == "handlechick"
replace label =  "Handled raw egg" if exposure == "handleregg"
replace label =  "Health drinks" if exposure == "healthdrink"
replace label =  "Live in a residential institution" if exposure == "instit"
replace label =  "Other berries" if exposure == "oberry"
replace label =  "Other dip" if exposure == "odip"
replace label =  "Other vegetables" if exposure == "oveg"
replace label =  "Pig ear pet treats" if exposure == "pigear"
replace label =  "Radishes" if exposure == "radish"
replace label =  "Attend school" if exposure == "school"
replace label =  "Other shellfish" if exposure == "shellfisho"
replace label =  "Other turkey" if exposure == "turkeyo"
replace label =  "Fermented vegetables (e.g. kimchi, sauerkraut)" if exposure == "vegferm"
replace label =  "White/yellow onions" if exposure == "whtonion"
replace label =  "Other melon" if exposure == "omelon"
replace label =  "Other berry" if exposure == "oberry"
replace label =  "Other fruit" if exposure == "ofruit"
replace label =  "Fruit smoothies (bottled)" if exposure == "prefruitsm"
replace label =  "Other snack food" if exposure == "osnack"
replace label =  "Soy Products" if exposure == "soyprod"
replace label =  "Guacamole" if exposure == "guac"
replace label =  "Pesto" if exposure == "pesto"
replace label =  "Other foods containing fresh berries or herbs" if exposure == "ofberher"
replace label =  "Other store-bought prepared salads" if exposure == "osaladstor"
replace label =  "Fresh salsa" if exposure == "salsa_f"
replace label =  "Salsa in a jar or can" if exposure == "salsa_jar"
replace label =  "Mixed berries" if exposure == "mixedb"
replace label =  "Pistachios" if exposure == "pistachio"
replace label =  "Other nut" if exposure == "onut"
replace label =  "Other beef" if exposure == "beefo"
replace label =  "Other pork" if exposure == "porko"
replace label =  "Game meat" if exposure == "game"
replace label =  "Other meat" if exposure == "meato"
replace label =  "Raw meat" if exposure == "meatraw"
replace label =  "Shawarma/donair*" if exposure == "shawarma"
replace label =  "Corned beef" if exposure == "cornedbeef"
replace label =  "Crustaceans" if exposure == "crust"
replace label =  "Other fish" if exposure == "fisho"
replace label =  "Other seafood" if exposure == "seafoodo"
replace label =  "Cockles" if exposure == "cockles"
replace label =  "Other unpasteurized dairy products" if exposure == "odairyunp"
replace label =  "Cheese slices bought at deli counter" if exposure == "cheesedel"
replace label =  "Frozen dairy desserts" if exposure == "frozendairy"
replace label =  "Non-dairy cheese" if exposure == "cheesenond"
replace label =  "Other dairy" if exposure == "dairyo"
replace label =  "Granola" if exposure == "granola"
replace label =  "Other salad" if exposure == "osal"
replace label =  "Other frozen food" if exposure == "ofrozenfd"
replace label = "Store-bought fresh beef patties" if exposure == "fbeefpatties"
replace label = "Dried fruit" if exposure == "dryfruit"
